apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-busybox  # No spaces in the name
spec:
  replicas: 3
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - name: busybox
        image: busybox
        command:
        - "sh"
        - "-c"
        - "sleep 5 && echo 'hello from busy box'"
